#!/usr/bin/env python
!pip install trimesh
# Import the necessary libraries
import random
import numpy as np
from PIL import Image

# Define the dimensions of the cube
#width = 4
#height = 4
#depth = 4

# Create an array of vertex positions for the cube
vertices = np.array([
  (-1, -1, -1), # 0
  (1, -1, -1),  # 1
  (1, 1, -1),   # 2
  (-1, 1, -1),  # 3
  (-1, -1, 1),  # 4
  (1, -1, 1),   # 5
  (1, 1, 1),    # 6
  (-1, 1, 1),   # 7
], dtype=np.float32)

# Create an array of vertex indices for the triangles
triangles = [
  (0, 1, 2), # front
  (2, 3, 0),
  (1, 5, 6), # right
  (6, 2, 1),
  (5, 4, 7), # back
  (7, 6, 5),
  (4, 0, 3), # left
  (3, 7, 4),
  (4, 5, 1), # bottom
  (1, 0, 4),
  (3, 2, 6), # top
  (6, 7, 3),
]
# Create a .png file for the texture map
image = Image.new('RGB', (2, 2))
pixels = image.load()

# Generate random pixel colors for the texture map
"""
for x in range(2):
  for y in range(2):
    #pixels[x, y] = (0, 0, 255)
    pixels[x,y]=(random.randint(0,255),random.randint(0,255),random.randint(0,255))
# Save the texture map to a .png file
"""
pixels[0,0]=(0, 0, 255)
pixels[0,1]=(0, 0, 255)
pixels[1,0]=(255, 0, 0)
pixels[1,1]=(255, 0, 0)
image.save('texture.png', 'PNG')

# Open a file for the .obj file
with open('model.obj', 'w') as f:
  # Write the header for the .obj file
  f.write('# Generated by Python\n')
  f.write('mtllib model.mtl\n')
  f.write('o model\n')

  # Write the vertex positions to the .obj file
  for vertex in vertices:
    f.write('v %f %f %f\n' % (vertex[0], vertex[1], vertex[2]))

  # Write the texture coordinates to the .obj file
  f.write('vt 0.0 0.0\n')
  f.write('vt 1.0 0.0\n')
  f.write('vt 1.0 1.0\n')
  f.write('vt 0.0 1.0\n')

  # Write the triangles to the .obj file
  f.write('usemtl material\n')
  #for triangle in triangles:
       #f.write('f %d/%d %d/%d %d/%d\n' % (triangle[0] + 1, triangle[0] + 1, triangle[1] + 1, triangle[1] + 1, triangle[2] + 1, triangle[2] + 1))
  f.write('f 1/1 2/1 3/1\n')
  f.write('f 3/3 2/3 6/3')
# Open a file for the .mtl file
with open('model.mtl', 'w') as f:
  # Write the header for the .mtl file
  f.write('# Generated by Python\n')
  f.write('newmtl material\n')
  f.write('map_Kd texture.png\n')